[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pycgc"
version = "0.1.0"
authors = [{ name = "Didas72" }]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [ "typer", "pycparser" ]


[project.scripts]
pyincp = "pycgc._cli:main"

[tool.setuptools.packages.find]
include = ["pycgc*"]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	# Conflicting
	"D203",
	"D212",
	"COM812",

	# Allow 'TODO' and 'HACK' in code
	"FIX002",
	"TD002",
	"TD003",
	"FIX004",
]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["S101", "D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
strict = true
